<%@ Page Title="" Language="C#" MasterPageFile="~/User.Master" AutoEventWireup="true" CodeBehind="MemberApproval.aspx.cs" Inherits="Society_management.MemberApproval" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="HeadContent" runat="server">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f8f9fa;
        }

        h2 {
            color: #2c3e50;
            padding-bottom: 10px;
            font-weight: 700;
        }

        /* Override GridView table styles to fit Bootstrap */
        /* Applying these directly to the table class given by ASP.NET GridView to avoid conflict */
        .table { /* This targets the table generated by GridView with CssClass="table" */
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 0 12px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            overflow: hidden; /* Important for rounded corners with shadow */
            margin-bottom: 1.5rem; /* Add some space below the table */
        }

        .table th, .table td { /* Target th/td within tables with class "table" */
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
            vertical-align: middle;
            white-space: nowrap; /* Prevent text wrapping in table cells by default */
        }

        .table th { /* Target table headers */
            background-color: gray;
            color: white;
            font-weight: 600;
        }

        .table tr:hover { /* Table row hover effect */
            background-color: #f1f3f5;
        }

        /* Styles for Approve/Reject buttons within the GridView */
        /* Use a more specific class for these buttons */
        .gridview-action-btn {
            padding: 6px 10px; /* Slightly adjusted padding */
            font-weight: 600;
            border-radius: 5px;
            border: none;
            cursor: pointer;
            min-width: 80px; /* Ensure a minimum width */
            margin-right: 5px; /* Space between buttons */
            white-space: nowrap; /* Keep button text on one line */
            display: inline-block; /* Ensure it respects margins */
        }

        .gridview-action-btn.btn-success { /* Target Bootstrap's btn-success for custom look */
            background-color: #2ecc71;
            color: white;
        }

        .gridview-action-btn.btn-success:hover {
            background-color: #27ae60;
        }

        .gridview-action-btn.btn-danger { /* Target Bootstrap's btn-danger for custom look */
            background-color: #e74c3c;
            color: white;
        }

        .gridview-action-btn.btn-danger:hover {
            background-color: #c0392b;
        }

        /* Message label styles */
        #lblMessage { /* Assuming this ID is for a single message label outside the grid */
            display: block;
            margin: 15px 0;
            padding: 12px 15px;
            border-radius: 6px;
            font-weight: 600;
            font-size: 1rem;
            text-align: center;
        }

        .success {
            background-color: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .error {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }

        /* External Button Group Container */
        .action-button-group {
            display: flex;
            flex-wrap: nowrap; /* Prevent wrapping by default */
            justify-content: flex-end;
            gap: 15px;
            width: 100%;
            margin-bottom: 1.5rem; /* Space below button group */
        }

        /* Base Button Styles for external buttons */
        .btn-register-notice,
        .btn-view-notice {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            padding: 12px 24px;
            text-decoration: none;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 16px;
            font-weight: 600;
            border-radius: 8px;
            transition: all 0.3s ease;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            white-space: nowrap; /* Keep button text on one line */
        }

        /* Register Button */
        .btn-register-notice {
            background-color: #3498db;
            color: white;
        }

        .btn-register-notice:hover {
            background-color: #2980b9;
            transform: translateY(-3px);
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
            text-decoration: none;
            color: white;
        }

        /* View Button */
        .btn-view-notice {
            background-color: #2ecc71;
            color: white;
        }

        .btn-view-notice:hover {
            background-color: #27ae60;
            transform: translateY(-3px);
            text-decoration: none;
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
            color: white;
        }

        /* Icons */
        .btn-register-notice i,
        .btn-view-notice i {
            margin-right: 10px;
            font-size: 18px;
        }

        /* Active State */
        .btn-register-notice:active,
        .btn-view-notice:active {
            transform: scale(0.98);
        }

        /* Focus State */
        .btn-register-notice:focus,
        .btn-view-notice:focus {
            outline: none;
        }

        .btn-register-notice:focus {
            box-shadow: 0 0 0 3px rgba(52, 152, 219, 0.5);
        }

        .btn-view-notice:focus {
            box-shadow: 0 0 0 3px rgba(46, 204, 113, 0.5);
        }

        /* Responsive Design for external buttons */
        /* Only stack if screen is very small, otherwise keep them inline */
        @media (max-width: 575.98px) { /* Adjust breakpoint for stacking, default Bootstrap sm breakpoint */
            .action-button-group {
                flex-direction: column;
                align-items: center; /* Center buttons when stacked */
                gap: 10px;
            }
            
            .btn-register-notice,
            .btn-view-notice {
                width: 100%;
                max-width: 300px; /* Optional: cap width when 100% */
                padding: 15px 20px;
                font-size: 18px;
                text-align: center;
            }
        }
        /* =========================================
   EMPTY STATE COMPONENT 
========================================= */
.empty-state-container {
    padding: 60px 20px;
    text-align: center;
    background-color: #ffffff;
    border-radius: 1rem;
    border: 1px solid #e2e8f0;
    box-shadow: 0 4px 6rem rgba(0,0,0,0.05);
    margin-top: 15px;
    width: 100%;
}

.empty-state-icon {
    font-size: 4rem;
    color: #3498db;
    opacity: 0.2;
    margin-bottom: 1.5rem;
    display: inline-block;
    animation: float 3s ease-in-out infinite;
}

@keyframes float {
    0% { transform: translateY(0px); }
    50% { transform: translateY(-10px); }
    100% { transform: translateY(0px); }
}

.empty-state-title {
    color: #1e293b;
    font-weight: 700;
    margin-bottom: 10px;
}
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="BreadcrumbContent" runat="server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="PageHeaderContent" runat="server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="PageHeaderButtons" runat="server">
    <div class="action-button-group">
        <a href="MemberSchedule.aspx" class="btn-register-notice">
            <i class="fas fa-plus-circle"></i> Scheduled Visitor
        </a>
        <a href="Visitor_List.aspx" class="btn-view-notice">
            <i class="fas fa-users"></i> Visitors
        </a>
    </div>
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container">
        
        <%-- ── Empty State Panel: Shows when grid has 0 items ── --%>
        <asp:Panel ID="pnlEmpty" runat="server" Visible="false">
            <div class="empty-state-container">
                <div class="empty-state-icon">
                    <i class="fas fa-id-badge"></i>
                </div>
                <h3 class="empty-state-title">No Pending Gate Requests</h3>
                <p class="text-muted mb-0">
                    You have no visitors waiting at the security gate at the moment.
                </p>
            </div>
        </asp:Panel>

        <%-- ── Data Content Placeholder Wrapper ── --%>
        <asp:PlaceHolder ID="phDataContent" runat="server">
            <div class="table-responsive">
                <asp:GridView ID="gvPendingVisitors" runat="server" AutoGenerateColumns="False" CssClass="table"
                    OnRowCommand="gvPendingVisitors_RowCommand">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Visitor Name" ItemStyle-CssClass="align-middle" />
                        <asp:BoundField DataField="ContactNumber" HeaderText="Contact Number" ItemStyle-CssClass="align-middle" />
                        <asp:BoundField DataField="VisitPurpose" HeaderText="Purpose" ItemStyle-CssClass="align-middle" />
                        <asp:BoundField DataField="VisitDateTime" HeaderText="Visit Time" DataFormatString="{0:g}" ItemStyle-CssClass="align-middle" />
                        <asp:BoundField DataField="MemberName" HeaderText="Meeting With" ItemStyle-CssClass="align-middle" />
                        <asp:TemplateField HeaderText="Action">
                            <ItemTemplate>
                                <div class="d-flex flex-nowrap justify-content-start align-items-center">
                                    <asp:Button ID="btnApprove" runat="server" Text="Approve" CommandName="Approve"
                                        CommandArgument='<%# Eval("VisitorID") %>' CssClass="gridview-action-btn btn-success" />
                                    <asp:Button ID="btnReject" runat="server" Text="Reject" CommandName="Reject"
                                        CommandArgument='<%# Eval("VisitorID") %>' CssClass="gridview-action-btn btn-danger" />
                                </div>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </div>
        </asp:PlaceHolder>

        <%-- Old fallback panel completely removed; Toast notification elements stay intact below --%>
        <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
            <div id="customToast" class="toast align-items-center text-white bg-success border-0" role="alert">
                <div class="d-flex">
                    <div class="toast-body" id="toastMessage">Success!</div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
                </div>
            </div>
        </div>

    </div>
</asp:Content><asp:Content ID="Content7" ContentPlaceHolderID="ScriptsContent" runat="server">

    <script>
        function showToast(message, isSuccess) {
            const toastEl = document.getElementById('customToast');
            const toastBody = document.getElementById('toastMessage');

            toastBody.textContent = message;

            if (isSuccess) {
                toastEl.classList.remove('bg-danger');
                toastEl.classList.add('bg-success');
            } else {
                toastEl.classList.remove('bg-success');
                toastEl.classList.add('bg-danger');
            }

            const toast = new bootstrap.Toast(toastEl);
            toast.show();
        }
    </script>
</asp:Content>